name: 'Test compilation'

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  formatting_check:
    name: Formatting Check
    runs-on: 'ubuntu-latest'
    strategy:
        matrix:
            path:
                - 'output/src/GameEngine/*.cpp'
                - 'output/src/GameEngine/*.hpp'
    steps:
        - uses: 'actions/checkout@v3'
        - name: 'Check formatting'
          uses: 'jidicula/clang-format-action@v4.11.0'
          with:
            clang-format-version: '17'
            check-path: ${{ matrix.path }}
            fallback-style: 'Mozilla'

  test_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Check compilation'
        run: 'bash output/compile.sh'
        timeout-minutes: 5
