name: 'Test compilation'

on:
  workflow_run:
    workflows: ["Formatting Check"]
    types:
      - completed

jobs:
  test_compilation:
    name: Test compilation EPITECH docker
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Check compilation'
        run: 'bash output/compile.sh'
        timeout-minutes: 5
