name: 'Integrity check'

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  formatting_check:
    name: 'Formatting Check'
    runs-on: 'ubuntu-latest'
    steps:
        - uses: 'actions/checkout@v3'
        - name: 'Check formatting'
          uses: 'jidicula/clang-format-action@v4.11.0'
          with:
            clang-format-version: '17'
            check-path: 'output/src'
            fallback-style: 'Mozilla'

  test_compilation:
    strategy:
      matrix:
        platform:
            - {
                os: ubuntu-latest,
                target: linux-x64
            }
            - {
                os: ubuntu-latest,
                target: linux-x86
            }
            - {
                os: ubuntu-latest,
                target: linux-arm
            }
            - {
                os: ubuntu-latest,
                target: windows-x64
            }
            - {
                os: ubuntu-latest,
                target: windows-x86
            }
            - {
                os: ubuntu-latest,
                target: windows-arm
            }
            - {
                os: ubuntu-latest,
                target: macos-x64
            }
            - {
                os: ubuntu-latest,
                target: macos-x86
            }
            - {
                os: ubuntu-latest,
                target: macos-arm
            }
    name: 'Test Compilation EPITECH Docker'
    needs: formatting_check
    runs-on: ${{ matrix.platform.os }}
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - uses: 'actions/checkout@v3'
      - name: 'Check Compilation'
        run: './vcpkg_cross-build.sh ${{ matrix.platform.target }}'
        timeout-minutes: 5
