name: 'Test compilation'

on:
  pull_request:
    branches: [ 'main', 'dev' ]

jobs:
  setup_cpp:
    runs-on: ubuntu-latest
    steps:
    - name: Setup CPP
      uses: actions/setup-cpp@v3
      with:
        cpp-version: "latest"

    - name: Install clang-format
      run: sudo apt-get install -y clang-format

  test_code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check code style
        run: bash output/check_format.sh
        timeout-minutes: 1

  test_compilation:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check compilation
        run: bash output/compile.sh
        timeout-minutes: 5
